version: "3.8"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
  ui:
    build: ./ui
    container_name: ui_container
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  db:
    build: ./db
    container_name: postgres_container
    ports:
      -"5432:5432"

