version: "3.8"
services:
  api:
    build: ./api
    image: vinibjazevich/react-fullstack-api
    container_name: api_container
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
  ui:
    build: ./ui
    image: vinibjazevich/react-fullstack-ui
    container_name: ui_container
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  db:
    image: postgres:14-alpine
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local