FROM postgres:14-alpine

#  docker run --name local-postgres -p 5432:5432 -e POSTGRES_PASSWORD=mypassword -e POSTGRES_USER=admin -d postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_USER=admin

EXPOSE 5432